name: Test

on:
pull_request:
  branches: [main]

# top-level call-out of the different tasks within the workflow
jobs:
# job id
test:
    name: Test
    runs-on: ubuntu-latest

    # list of steps to complete in the workflow, in order
    steps:
    # extend from these published, pre-configured actions
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    with:
        # the node version for the setup-node action
        node-version: 16.x
    # Install packages and run tests
    - run: npm ci
    - run: npm test

  # test:
  #   name: Test
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 16.x

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Run tests
  #       run: npm test